version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: location_micro_service
    ports:
      - "8080:8080"