services:
  redis:
    image: redis:latest
    container_name: redis_location_service
    ports:
      - "6380:6379"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6310
    volumes:
      - redis_data:/data 

  fast-api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: location_micro_service
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=location_service
      - JWT_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=6310
    command: uvicorn apps.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app/app 

volumes:
  redis_data: